export default function RemindersPage() {
  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold">Reminders</h1>
      <p className="text-gray-500 mt-2">
        Follow-ups and smart reminders generated by SAVIOUR.
      </p>
    </div>
  );
}